In [8]:
import numpy as np

# 1D array
a = np.array([1,2,3,4,5])

# 2D array
b = np.array([[1,2],[3,4]])

# Zeros
c = np.zeros((3,4))
c

# # Ones
d = np.ones((2,5))
d

# # Identity matrix
e = np.eye(4)
e

# # Range
f = np.arange(1,20,2)
f

# # Linearly spaced values
g = np.linspace(0,10,5)
g

# # Random numbers
h = np.random.rand(3,3)
h

# # Random integers
i = np.random.randint(1,100,(4,4))
i

array([[78,  8, 18, 13],
       [10, 57, 35,  4],
       [97, 40, 20, 31],
       [48, 52,  4,  7]])

In [15]:
a = np.random.randint(1,100,(4,5))

a.shape
a.size
a.ndim
a.dtype

dtype('int64')

In [29]:
a = np.arange(1,26).reshape(5,5)

a
a[0]
a[-1]
a[:, 0]
a[0,:]
a[2,2]
print(a[1:3, 1:3])

[[ 7  8]
 [12 13]]


In [33]:
a = np.arange(12)

# a.reshape(3,4)
# a.reshape(2,6)
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])